### ISSUE TITLE
lein uberjar: Release versions may not depend upon snapshots.

### ISSUE THREAD

**Issue by jiyinyiyong** [trhura/clojure-term-colors#2]
Request for an update:

```
➤➤ lein uberjar
Release versions may not depend upon snapshots.
Freeze snapshots to dated versions or set the LEIN_SNAPSHOTS_IN_RELEASE environment variable to override.
```

and this line is wrong: https://github.com/trhura/clojure-term-colors/blob/master/project.clj#L3

**Comment by ghost** [comment]
+1

**Comment by evanjbowling** [comment]
+1
You updated this in 925f1cc, but did not run:

```
lein deploy clojars
```

Can you publish the non-SNAPSHOT version?

**Comment by gfredericks** [comment]
In the meantime, you can use `[com.gfredericks.forks.clojure-term-colors/clojure-term-colors "0.1.0-71620a5"]`

**Comment by trhura** [comment]
Sorry for the delay, guys. Non-snapshot version published on clojars now.
